### ISSUE TITLE
Wrong file path

### ISSUE THREAD

**Issue by jasdehart** [Anish1202/cs5293sp23-project2#1] opened 2023-04-29 04:41 UTC
Hi,

You should consider updating this line. Your code does not run.

https://github.com/Anish1202/cs5293sp23-project2/blob/db39c849f0e25fa4af0ba48216a6b5a5cb50563e/project2.py#L48

**Comment by Anish1202** [comment] 2023-04-30 23:03
Hi jasmine,
The issue is fixed now, could you please check it .

**Closed as completed by Anish1202** 2023-04-30 23:03 UTC
